repos:
  -   repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.3
      hooks:
      -   id: seed-isort-config

  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
      -   id: isort

  -   repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
      -   id: black
          types: [python]

  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
      -   id: flake8
          additional_dependencies: ['flake8-bugbear>=19.8.0', 'flake8-comprehensions>=3.1.4', 'pep8-naming>=0.9.1']

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: debug-statements
      -   id: check-added-large-files
      -   id: check-merge-conflict
      -   id: mixed-line-ending
          args: ['--fix=lf']

  -   repo: https://github.com/mgedmin/check-manifest
      rev: "0.40"
      hooks:
      -   id: check-manifest
